import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Lato } from "next/font/google";
import "@/styles/index.scss";

export const metadata = {
	title: "Kangol Store",
	description: "Generated by create next app",
	icons: {
		icon: "/favicon.ico",
	},
};

const lato = Lato({ weight: "400", subsets: ["latin"] });

export const dynamic = "force-dynamic";

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={lato.className}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
