import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "@/styles/index.scss";

export const metadata = {
	title: "Kangol Store",
	description: "Generated by create next app",
	icons: {
		icon: "/favicon.ico",
	},
};

export const dynamic = "force-dynamic";

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
